slate_config ={'layers': [{'encoder': {'button': (1, 205),
                         'decrement': (1, 234),
                         'increment': (1, 233)},
             'joystick': {'button': (7, 1),
                          'x+': (8, [100, 0, 0]),
                          'x-': (8, [-100, 0, 0]),
                          'y+': (8, [0, 100, 0]),
                          'y-': (8, [0, -100, 0])},
             'key_shortcuts': [{'actions': (3, 'Slate'), 'assigned_key': 0},
                               {'actions': (3, 'Keypad'), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'Slate',
             'touch_shortcuts': [{'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'}]},
            {'encoder': {'button': (None, None),
                         'decrement': (None, None),
                         'increment': (None, None)},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (None, None), 'assigned_key': 0},
                               {'actions': (None, None), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'Youtube Controls',
             'touch_shortcuts': [{'actions': (2, [14]),
                                  'icon': 'icons/pr_play.bmp',
                                  'label': 'Play'},
                                 {'actions': (2, [14]),
                                  'icon': 'icons/pr_pause.bmp',
                                  'label': 'Pause'},
                                 {'actions': (2, [80]),
                                  'icon': 'icons/pr_rewind.bmp',
                                  'label': 'Rewind'},
                                 {'actions': (2, [79]),
                                  'icon': 'icons/pr_ffwd.bmp',
                                  'label': 'FastForward'},
                                 {'actions': (2, [225, 19]),
                                  'icon': 'icons/pr_previous.bmp',
                                  'label': 'Previous'},
                                 {'actions': (2, [225, 17]),
                                  'icon': 'icons/pr_next.bmp',
                                  'label': 'Next'},
                                 {'actions': (1, 234),
                                  'icon': 'icons/pr_voldown.bmp',
                                  'label': 'Vol -'},
                                 {'actions': (1, 233),
                                  'icon': 'icons/pr_volup.bmp',
                                  'label': 'Vol +'},
                                 {'actions': (2, [9]),
                                  'icon': 'icons/pr_fullscreen.bmp',
                                  'label': 'Fullscreen'},
                                 {'actions': (2, [225, 54]),
                                  'icon': 'icons/pr_slow.bmp',
                                  'label': 'Slow'},
                                 {'actions': (2, [225, 55]),
                                  'icon': 'icons/pr_fast.bmp',
                                  'label': 'Fast'},
                                 {'actions': (2, [16]),
                                  'icon': 'icons/pr_mute.bmp',
                                  'label': 'Mute'}]}]}
