slate_config ={'layers': [{'encoder': {'button': (1, 205),
                         'decrement': (1, 234),
                         'increment': (1, 233)},
             'joystick': {'button': (7, 1),
                          'x+': (8, [-100, 0, 0]),
                          'x-': (8, [100, 0, 0]),
                          'y+': (8, [0, 100, 0]),
                          'y-': (8, [0, -100, 0])},
             'key_shortcuts': [{'actions': (3, 'Slate'), 'assigned_key': 0},
                               {'actions': (3, 'Keypad'), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'Slate',
             'touch_shortcuts': [{'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (2, []),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'},
                                 {'actions': (3, 'Slate'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate Logo'}]},
            {'encoder': {'button': (None, None),
                         'decrement': (None, None),
                         'increment': (None, None)},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (None, None), 'assigned_key': 0},
                               {'actions': (None, None), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'awsdadw',
             'touch_shortcuts': [{'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'}]},
            {'encoder': {'button': (None, None),
                         'decrement': (None, None),
                         'increment': (None, None)},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (None, None), 'assigned_key': 0},
                               {'actions': (None, None), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'asdas',
             'touch_shortcuts': [{'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'}]},
            {'encoder': {'button': (None, None),
                         'decrement': (None, None),
                         'increment': (None, None)},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (None, None), 'assigned_key': 0},
                               {'actions': (None, None), 'assigned_key': 1},
                               {'actions': [None, None], 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'asdddasdad',
             'touch_shortcuts': [{'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label2'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'}]},
            {'encoder': {'button': (None, None),
                         'decrement': (None, None),
                         'increment': (None, None)},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (None, None), 'assigned_key': 0},
                               {'actions': (None, None), 'assigned_key': 1},
                               {'actions': [None, None], 'assigned_key': 2},
                               {'actions': (None, None), 'assigned_key': 3},
                               {'actions': (None, None), 'assigned_key': 4},
                               {'actions': (None, None), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (None, None), 'assigned_key': 7}],
             'name': 'vvfdfv',
             'touch_shortcuts': [{'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'},
                                 {'actions': (None, None),
                                  'icon': 'icons/pr_blank.bmp',
                                  'label': 'Label'}]}]}
