slate_config ={'layers': [{'encoder': {'button': (1, 205),
                         'decrement': (1, 234),
                         'increment': (1, 233)},
             'joystick': {'button': (7, 1),
                          'x+': (8, [100, 0, 0]),
                          'x-': (8, [-100, 0, 0]),
                          'y+': (8, [0, 100, 0]),
                          'y-': (8, [0, -100, 0])},
             'key_shortcuts': [{'actions': (2, [224, 6]), 'assigned_key': 0},
                               {'actions': (2, [224, 25]), 'assigned_key': 1},
                               {'actions': (None, None), 'assigned_key': 2},
                               {'actions': (1, 111), 'assigned_key': 3},
                               {'actions': (2, [224, 4]), 'assigned_key': 4},
                               {'actions': (2, [224, 9]), 'assigned_key': 5},
                               {'actions': (None, None), 'assigned_key': 6},
                               {'actions': (1, 112), 'assigned_key': 7}],
             'name': 'Slate',
             'touch_shortcuts': [{'actions': (9,
                                              '"C:\\Program Files '
                                              '(x86)\\Steam\\steam.exe"'),
                                  'icon': 'icons/td_steam.bmp',
                                  'label': 'Steam'},
                                 {'actions': (9,
                                              '"C:\\Program '
                                              'Files\\Google\\Chrome\\Application\\chrome.exe"'),
                                  'icon': 'icons/td_chrome.bmp',
                                  'label': 'Chrome'},
                                 {'actions': (9,
                                              'C:\\Users\\Jacob\\AppData\\Local\\Discord\\Update.exe '
                                              '--processStart Discord.exe'),
                                  'icon': 'icons/td_discord.bmp',
                                  'label': 'Discord'},
                                 {'actions': (9,
                                              'C:\\Users\\Jacob\\AppData\\Roaming\\Spotify\\Spotify.exe'),
                                  'icon': 'icons/td_spotify.bmp',
                                  'label': 'Spotify'},
                                 {'actions': (9,
                                              '"C:\\Program '
                                              'Files\\Adobe\\Adobe Photoshop '
                                              'CC 2019\\Photoshop.exe"'),
                                  'icon': 'icons/td_photoshop.bmp',
                                  'label': 'Photoshop'},
                                 {'actions': (9,
                                              '"C:\\Program '
                                              'Files\\Adobe\\Adobe Premiere '
                                              'Pro CC 2019\\Adobe Premiere '
                                              'Pro.exe"'),
                                  'icon': 'icons/td_premiere.bmp',
                                  'label': 'Premiere Pro'},
                                 {'actions': (9,
                                              '"C:\\Program Files\\Microsoft '
                                              'VS Code\\Code.exe"'),
                                  'icon': 'icons/td_vscode.bmp',
                                  'label': 'VSCode'},
                                 {'actions': (9, 'calc'),
                                  'icon': 'icons/td_calc.bmp',
                                  'label': 'Calculator'},
                                 {'actions': (2, [227, 43]),
                                  'icon': 'icons/td_switchapp.bmp',
                                  'label': 'Task View'},
                                 {'actions': (2, [224, 225, 41]),
                                  'icon': 'icons/td_taskmanager.bmp',
                                  'label': 'Task Manager'},
                                 {'actions': (2, [227, 229, 22]),
                                  'icon': 'icons/td_snip.bmp',
                                  'label': 'Snipping Tool'},
                                 {'actions': (3,
                                              'Slate can type text for you!'),
                                  'icon': 'icons/slate.bmp',
                                  'label': 'Slate'}]},
            {'encoder': {'button': (2, [14]),
                         'decrement': (2, [80]),
                         'increment': (2, [79])},
             'joystick': {'button': (None, None),
                          'x+': (None, None),
                          'x-': (None, None),
                          'y+': (None, None),
                          'y-': (None, None)},
             'key_shortcuts': [{'actions': (2, [14]), 'assigned_key': 0},
                               {'actions': (2, [14]), 'assigned_key': 1},
                               {'actions': (2, [80]), 'assigned_key': 2},
                               {'actions': (2, [79]), 'assigned_key': 3},
                               {'actions': (2, [9]), 'assigned_key': 4},
                               {'actions': (2, [54]), 'assigned_key': 5},
                               {'actions': (2, [55]), 'assigned_key': 6},
                               {'actions': (2, [16]), 'assigned_key': 7}],
             'name': 'Youtube Controls',
             'touch_shortcuts': [{'actions': (2, [14]),
                                  'icon': 'icons/pr_play.bmp',
                                  'label': 'Play'},
                                 {'actions': (2, [14]),
                                  'icon': 'icons/pr_pause.bmp',
                                  'label': 'Pause'},
                                 {'actions': (2, [80]),
                                  'icon': 'icons/pr_rewind.bmp',
                                  'label': 'Rewind'},
                                 {'actions': (2, [79]),
                                  'icon': 'icons/pr_ffwd.bmp',
                                  'label': 'FastForward'},
                                 {'actions': (2, [225, 19]),
                                  'icon': 'icons/pr_previous.bmp',
                                  'label': 'Previous'},
                                 {'actions': (2, [225, 17]),
                                  'icon': 'icons/pr_next.bmp',
                                  'label': 'Next'},
                                 {'actions': (1, 234),
                                  'icon': 'icons/pr_voldown.bmp',
                                  'label': 'Vol -'},
                                 {'actions': (1, 233),
                                  'icon': 'icons/pr_volup.bmp',
                                  'label': 'Vol +'},
                                 {'actions': (2, [9]),
                                  'icon': 'icons/pr_fullscreen.bmp',
                                  'label': 'Fullscreen'},
                                 {'actions': (2, [225, 54]),
                                  'icon': 'icons/pr_slow.bmp',
                                  'label': 'Slow'},
                                 {'actions': (2, [225, 55]),
                                  'icon': 'icons/pr_fast.bmp',
                                  'label': 'Fast'},
                                 {'actions': (2, [16]),
                                  'icon': 'icons/pr_mute.bmp',
                                  'label': 'Mute'}]}]}
