# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_screenkey.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newScreenKeyDialog(object):
    def setupUi(self, newScreenKeyDialog):
        newScreenKeyDialog.setObjectName("newScreenKeyDialog")
        newScreenKeyDialog.resize(400, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newScreenKeyDialog.sizePolicy().hasHeightForWidth())
        newScreenKeyDialog.setSizePolicy(sizePolicy)
        newScreenKeyDialog.setMinimumSize(QtCore.QSize(400, 215))
        newScreenKeyDialog.setMaximumSize(QtCore.QSize(400, 215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("slate_windowicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        newScreenKeyDialog.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(newScreenKeyDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 401, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setGeometry(QtCore.QRect(110, 171, 161, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.screenkey_name_label = QtWidgets.QLabel(self.widget)
        self.screenkey_name_label.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.screenkey_name_label.setObjectName("screenkey_name_label")
        self.screenkey_name = QtWidgets.QLineEdit(self.widget)
        self.screenkey_name.setGeometry(QtCore.QRect(80, 20, 111, 20))
        self.screenkey_name.setObjectName("screenkey_name")
        self.screenkey_macro_label = QtWidgets.QLabel(self.widget)
        self.screenkey_macro_label.setGeometry(QtCore.QRect(20, 80, 51, 21))
        self.screenkey_macro_label.setObjectName("screenkey_macro_label")
        self.screenkey_macro = QtWidgets.QComboBox(self.widget)
        self.screenkey_macro.setGeometry(QtCore.QRect(80, 80, 111, 22))
        self.screenkey_macro.setObjectName("screenkey_macro")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_image_label = QtWidgets.QLabel(self.widget)
        self.screenkey_image_label.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.screenkey_image_label.setObjectName("screenkey_image_label")
        self.screnkey_image_path = QtWidgets.QLineEdit(self.widget)
        self.screnkey_image_path.setGeometry(QtCore.QRect(80, 50, 111, 20))
        self.screnkey_image_path.setObjectName("screnkey_image_path")
        self.fileSelect = QtWidgets.QToolButton(self.widget)
        self.fileSelect.setGeometry(QtCore.QRect(200, 50, 25, 21))
        self.fileSelect.setObjectName("fileSelect")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(223, 20, 41, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.image_preview_label = QtWidgets.QLabel(self.widget)
        self.image_preview_label.setGeometry(QtCore.QRect(300, 90, 47, 16))
        self.image_preview_label.setObjectName("image_preview_label")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(newScreenKeyDialog)
        self.buttonBox.accepted.connect(newScreenKeyDialog.accept)
        self.buttonBox.rejected.connect(newScreenKeyDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newScreenKeyDialog)

    def retranslateUi(self, newScreenKeyDialog):
        _translate = QtCore.QCoreApplication.translate
        newScreenKeyDialog.setWindowTitle(_translate("newScreenKeyDialog", "On-Screen Key"))
        self.screenkey_name_label.setText(_translate("newScreenKeyDialog", "Label:"))
        self.screenkey_macro_label.setText(_translate("newScreenKeyDialog", "Macro:"))
        self.screenkey_macro.setItemText(0, _translate("newScreenKeyDialog", "None"))
        self.screenkey_macro.setItemText(1, _translate("newScreenKeyDialog", "Hotkey"))
        self.screenkey_macro.setItemText(2, _translate("newScreenKeyDialog", "String"))
        self.screenkey_macro.setItemText(3, _translate("newScreenKeyDialog", "Media Control"))
        self.screenkey_macro.setItemText(4, _translate("newScreenKeyDialog", "Window Sizing"))
        self.screenkey_macro.setItemText(5, _translate("newScreenKeyDialog", "Mouse"))
        self.screenkey_image_label.setText(_translate("newScreenKeyDialog", "Image:"))
        self.fileSelect.setText(_translate("newScreenKeyDialog", "..."))
        self.image_preview_label.setText(_translate("newScreenKeyDialog", "<html><head/><body><p align=\"center\">IMAGE</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newScreenKeyDialog = QtWidgets.QDialog()
    ui = Ui_newScreenKeyDialog()
    ui.setupUi(newScreenKeyDialog)
    newScreenKeyDialog.show()
    sys.exit(app.exec_())
