# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_layer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newLayerDialog(object):
    def setupUi(self, newLayerDialog):
        newLayerDialog.setObjectName("newLayerDialog")
        newLayerDialog.resize(230, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newLayerDialog.sizePolicy().hasHeightForWidth())
        newLayerDialog.setSizePolicy(sizePolicy)
        newLayerDialog.setMinimumSize(QtCore.QSize(230, 100))
        newLayerDialog.setMaximumSize(QtCore.QSize(230, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("slate_windowicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        newLayerDialog.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(newLayerDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 231, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setGeometry(QtCore.QRect(30, 51, 161, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.newlayer_name = QtWidgets.QLineEdit(self.widget)
        self.newlayer_name.setGeometry(QtCore.QRect(20, 30, 191, 20))
        self.newlayer_name.setObjectName("newlayer_name")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 0, 91, 31))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(newLayerDialog)
        QtCore.QMetaObject.connectSlotsByName(newLayerDialog)

    def retranslateUi(self, newLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        newLayerDialog.setWindowTitle(_translate("newLayerDialog", "Create New Layer"))
        self.label.setText(_translate("newLayerDialog", "New layer name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newLayerDialog = QtWidgets.QDialog()
    ui = Ui_newLayerDialog()
    ui.setupUi(newLayerDialog)
    newLayerDialog.show()
    sys.exit(app.exec_())
