# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\screenkey.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

COMBOBOX_MEDIA = [
    "Volume Up",
    "Volume Down",
    "Mute",
    "Play/Pause",
    "Stop",
    "Rewind",
    "Fast Forward",
    "Record",
    "Next Track",
    "Previous Track",
    "Eject",
    "Brightness Increase",
    "Brightness Decrease"
    ]

COMBOBOX_MOUSE = [
    "Mouse Up",
    "Mouse Down",
    "Mouse Left",
    "Mouse Right",
    "Left Button",
    "Right Button",
    "Middle Button"
]


class Ui_screenKeyDialog(object):
    def setupUi(self, screenKeyDialog):
        screenKeyDialog.setObjectName("screenKeyDialog")
        screenKeyDialog.resize(400, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(screenKeyDialog.sizePolicy().hasHeightForWidth())
        screenKeyDialog.setSizePolicy(sizePolicy)
        screenKeyDialog.setMinimumSize(QtCore.QSize(400, 215))
        screenKeyDialog.setMaximumSize(QtCore.QSize(400, 215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\slate_windowicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        screenKeyDialog.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(screenKeyDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 401, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setGeometry(QtCore.QRect(110, 171, 161, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.screenkey_name_label = QtWidgets.QLabel(self.widget)
        self.screenkey_name_label.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.screenkey_name_label.setObjectName("screenkey_name_label")
        self.screenkey_name = QtWidgets.QLineEdit(self.widget)
        self.screenkey_name.setGeometry(QtCore.QRect(80, 20, 121, 20))
        self.screenkey_name.setObjectName("screenkey_name")
        self.screenkey_name.setMaxLength(14)
        self.screenkey_macro_label = QtWidgets.QLabel(self.widget)
        self.screenkey_macro_label.setGeometry(QtCore.QRect(20, 80, 51, 21))
        self.screenkey_macro_label.setObjectName("screenkey_macro_label")
        self.screenkey_macro = QtWidgets.QComboBox(self.widget)
        self.screenkey_macro.setGeometry(QtCore.QRect(80, 80, 111, 22))
        self.screenkey_macro.setObjectName("screenkey_macro")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.addItem("")
        self.screenkey_macro.currentIndexChanged.connect(lambda: self.showInputForm("screenkey", self.screenkey_macro.currentIndex()))
        self.screenkey_image_label = QtWidgets.QLabel(self.widget)
        self.screenkey_image_label.setGeometry(QtCore.QRect(20, 50, 51, 21))
        self.screenkey_image_label.setObjectName("screenkey_image_label")
        self.screenkey_image_path = QtWidgets.QLineEdit(self.widget)
        self.screenkey_image_path.setGeometry(QtCore.QRect(80, 50, 111, 20))
        self.screenkey_image_path.setObjectName("screenkey_image_path")
        self.fileSelect = QtWidgets.QToolButton(self.widget)
        self.fileSelect.setGeometry(QtCore.QRect(200, 50, 25, 21))
        self.fileSelect.setObjectName("fileSelect")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(223, 20, 41, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.image_preview_label = QtWidgets.QLabel(self.widget)
        self.image_preview_label.setGeometry(QtCore.QRect(300, 90, 47, 16))
        self.image_preview_label.setObjectName("image_preview_label")
        self.screenkey_string = QtWidgets.QLineEdit(self.widget)
        self.screenkey_string.setEnabled(True)
        self.screenkey_string.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.screenkey_string.setObjectName("string")
        self.screenkey_combobox = QtWidgets.QComboBox(self.widget)
        self.screenkey_combobox.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.screenkey_combobox.setObjectName("combobox")
        self.screenkey_hotkey = QtWidgets.QKeySequenceEdit(self.widget)
        self.screenkey_hotkey.setEnabled(True)
        self.screenkey_hotkey.setGeometry(QtCore.QRect(20, 110, 201, 21))
        self.screenkey_hotkey.setObjectName("hotkey")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(screenKeyDialog)
        self.buttonBox.accepted.connect(screenKeyDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(screenKeyDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(screenKeyDialog)

    def retranslateUi(self, screenKeyDialog):
        _translate = QtCore.QCoreApplication.translate
        screenKeyDialog.setWindowTitle(_translate("screenKeyDialog", "On-Screen Key"))
        self.screenkey_name_label.setText(_translate("screenKeyDialog", "Label:"))
        self.screenkey_macro_label.setText(_translate("screenKeyDialog", "Macro:"))
        self.screenkey_macro.setItemText(0, _translate("screenKeyDialog", "None"))
        self.screenkey_macro.setItemText(1, _translate("screenKeyDialog", "Hotkey"))
        self.screenkey_macro.setItemText(2, _translate("screenKeyDialog", "String"))
        self.screenkey_macro.setItemText(3, _translate("screenKeyDialog", "Media Control"))
        self.screenkey_macro.setItemText(4, _translate("screenKeyDialog", "Window Sizing"))
        self.screenkey_macro.setItemText(5, _translate("screenKeyDialog", "Mouse"))
        self.screenkey_image_label.setText(_translate("screenKeyDialog", "Image:"))
        self.fileSelect.setText(_translate("screenKeyDialog", "..."))
        self.image_preview_label.setText(_translate("screenKeyDialog", "<html><head/><body><p align=\"center\">IMAGE</p></body></html>"))
    
    def showInputForm(self, prefix, macro_type_index):
        if macro_type_index == 0:
            getattr(self, '%s_hotkey' % prefix).setVisible(False)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(False)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(False)
            getattr(self, '%s_combobox' % prefix).clear()
        if macro_type_index == 1:
            getattr(self, '%s_hotkey' % prefix).setVisible(True)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(False)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(False)
            getattr(self, '%s_combobox' % prefix).clear()
        if macro_type_index == 2:
            getattr(self, '%s_hotkey' % prefix).setVisible(False)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(True)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(False)
            getattr(self, '%s_combobox' % prefix).clear()
        if macro_type_index == 3:
            getattr(self, '%s_hotkey' % prefix).setVisible(False)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(False)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(True)
            getattr(self, '%s_combobox' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).addItems(COMBOBOX_MEDIA)
        if macro_type_index == 4:
            getattr(self, '%s_hotkey' % prefix).setVisible(False)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(False)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(True)
            getattr(self, '%s_combobox' % prefix).clear()
        if macro_type_index == 5:
            getattr(self, '%s_hotkey' % prefix).setVisible(False)
            getattr(self, '%s_hotkey' % prefix).clear()
            getattr(self, '%s_string' % prefix).setVisible(False)
            getattr(self, '%s_string' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).setVisible(True)
            getattr(self, '%s_combobox' % prefix).clear()
            getattr(self, '%s_combobox' % prefix).addItems(COMBOBOX_MOUSE)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    screenKeyDialog = QtWidgets.QDialog()
    ui = Ui_screenKeyDialog()
    ui.setupUi(screenKeyDialog)
    screenKeyDialog.show()
    sys.exit(app.exec_())
